# Generated by Django 3.2.12 on 2022-05-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_alter_comments_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threads',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m'),
        ),
    ]
